### ISSUE TITLE
Exceptions occurs when using random code in generator in RandomColorizeFunction

### ISSUE THREAD

**Issue by plezy** [plezy/avatar-generator#1]
```
Failed to build avatar
com.talanlabs.avatargenerator.AvatarException: Failed to build avatar
	at com.talanlabs.avatargenerator.Avatar.buildAll(Avatar.java:128)
	at com.talanlabs.avatargenerator.Avatar.create(Avatar.java:71)
	at com.talanlabs.avatargenerator.Avatar.createAsPngBytes(Avatar.java:82)
....
Caused by: java.lang.ArrayIndexOutOfBoundsException: -5
	at java.util.Arrays$ArrayList.get(Arrays.java:3841)
	at com.talanlabs.avatargenerator.functions.RandomColorizeFunction.colorize(RandomColorizeFunction.java:30)
	at com.talanlabs.avatargenerator.Avatar.copyImage(Avatar.java:182)
	at com.talanlabs.avatargenerator.Avatar.buildAvatarImage(Avatar.java:171)
	at com.talanlabs.avatargenerator.Avatar.buildAll(Avatar.java:108)
	... 87 more
```

**Comment by plezy** [comment]
Problem origin seems to be the same as for #2.

Applying same modification.
