### ISSUE TITLE
Exceptions occurs when using random code in generator in RandomColorPaintBackgroundLayer

### ISSUE THREAD

**Issue by plezy** [plezy/avatar-generator#2]
Exception (similar to issue #1) occurs when generating Avatar with Random.nextLong()
```
Failed to build avatar
com.talanlabs.avatargenerator.AvatarException: Failed to build avatar
	at com.talanlabs.avatargenerator.Avatar.buildAll(Avatar.java:128)
	at com.talanlabs.avatargenerator.Avatar.create(Avatar.java:71)
	at com.talanlabs.avatargenerator.Avatar.createAsPngBytes(Avatar.java:82)
....
Caused by: java.lang.ArrayIndexOutOfBoundsException: -1
	at java.util.Arrays$ArrayList.get(Arrays.java:3841)
	at com.talanlabs.avatargenerator.layers.backgrounds.RandomColorPaintBackgroundLayer.apply(RandomColorPaintBackgroundLayer.java:28)
	at com.talanlabs.avatargenerator.Avatar.buildAll(Avatar.java:120)
	... 87 more
```

**Comment by plezy** [comment]
Line 28 of RandomColorPaintBackgroundLayer is 

`Color backColor = colors.get((int) (avatarInfo.getCode() % colors.size()));`

`getCode` is a `long` and may produce negative numbers. therefore the `%` (modulo) operator's result may be negative.

try to put the following code to ensure the result is always positive
```
		int idx = (int) (avatarInfo.getCode() % colors.size());
		if (idx < 0)
			idx += colors.size();
		Color backColor = colors.get(idx);
```
