### ISSUE TITLE
Exceptions occurs when using random code in generator in SmileyAvatar

### ISSUE THREAD

**Issue by plezy** [plezy/avatar-generator#3]
```
Failed to build avatar
com.talanlabs.avatargenerator.AvatarException: Failed to build avatar
	at com.talanlabs.avatargenerator.Avatar.buildAll(Avatar.java:128)
	at com.talanlabs.avatargenerator.Avatar.create(Avatar.java:71)
	at com.talanlabs.avatargenerator.Avatar.createAsPngBytes(Avatar.java:82)
...
Caused by: java.lang.ArrayIndexOutOfBoundsException: -5
	at java.util.Arrays$ArrayList.get(Arrays.java:3841)
	at com.talanlabs.avatargenerator.smiley.SmileyAvatar.lambda$newGhostAvatarBuilder$0(SmileyAvatar.java:125)
	at com.talanlabs.avatargenerator.Avatar.copyImage(Avatar.java:182)
	at com.talanlabs.avatargenerator.Avatar.buildAvatarImage(Avatar.java:171)
	at com.talanlabs.avatargenerator.Avatar.buildAll(Avatar.java:108)
	... 87 more
```

**Comment by plezy** [comment]
Probably the same problem as #2
